In [31]:
import math
import random
import numpy as np
import matplotlib.pyplot as plt
from fractions import Fraction as frac

# 1. Mathematik

Deutsch(norm), *English(kursiv)*

*Exploration in Markdown* -> $LaTex$ 

*Implementation in computer* -> **DataType**

*Implementation in Python* --> `function()` or `bool`

*Visualitation in Python* --> matplotlib.pyplot module `plt.function()`

In Python implementieren:
1. *Biuldin functions in python*
2. *math module*
3. *numpy module*
4. *skipy module*
5. *fractions module*


### Gleichung:

$a\approx b$ 

$ [a] $ -round

$ \lceil a \rceil $ -ceil

$ \lfloor a \rfloor $ - floor


input **float** $\rightarrow$ **function** `round()`,`math.ceil()`, `math.floor()` $\rightarrow$ output **integer** $\mathbb{Z}$

input **float,array** $\rightarrow$ **function** `np.round()`,`np.around()`,`np.ceil()`, `np.floor()` $\rightarrow$ output **float,array** $\mathbb{Q}$

$a = b $ $\rightarrow$  **boolien operators** `a == b ` $\rightarrow$ output `True`(`1`) or `False`(`0`)

$a \neq b$ $\rightarrow$ **bool** `a!=b` $\rightarrow$ output `True`(`1`) or `False`(`0`)

$a<b$ $\rightarrow$ **bool** `a<b` $\rightarrow$ output `True`(`1`) or `False`(`0`)

$a>b$ $\rightarrow$ **bool** `a>b` $\rightarrow$ output `True`(`1`) or `False`(`0`)

$a≥b$ $\rightarrow$ **bool** `a>=b` $\rightarrow$ output `True`(`1`) or `False`(`0`)

$a≤b$ $\rightarrow$ **bool** `a<=b` $\rightarrow$ output `True`(`1`) or `False`(`0`)




In [26]:

b=-5.87
print(type(math.ceil(b)),math.ceil(b)) # round to up
print(math.floor(b)) # round to down
print(type(round(b)),round(b))

print()
a = - 3.14
print(type(np.ceil(a))) # round to up
print(np.floor(a))
print(np.round(a))
print()
print(a==b)
print(a!=b)
print(a<b)
print(a>b)
print(a>=b)
print(a<=b)

<class 'int'> -5
-6
<class 'int'> -6

<class 'numpy.float64'>
-4.0
-3.0

False
True
False
True
True
False


### Operationen:

Addition:

$a + b$ $\to$ **bool** `+` $\to$ output as input

Subtraction:

$a - b$ $\to$ **bool** `-` $\to$ output as input

Multiplikation:

$a \cdot b$ $\to $ **function** `*` $\to$ output $\mathbb{Q}$

$a \cdot b$ $\to $ **function** `np.multiply()` $\to$ output $\mathbb{Q}$

Division:

$a : b$ ,$a \div b$  $\to $ **function** `/` $\to$ output $\mathbb{Q}$




In [28]:
addition =2.3+3.5
div=3/6

print(type(div), div)

<class 'float'> 0.5



### Fraction/Ratio

$a / b$ , $ \frac{a}{b}$ 

input **number** $\mathbb{Q}$  $\to$ **function** `frac()` $\to$ **fraction** `int/int` $\mathbb{Z}$

Percentage- Ratio in Fraction of 100

$ a \% b $ 

In [89]:
fract= frac(16/15)
print(fract)
fract_lim=frac(16/15).limit_denominator(100)
print(fract_lim,type(fract_lim))


4803839602528529/4503599627370496
16/15 <class 'fractions.Fraction'>
16.0


## Betrag *Absolute value*

$ \vert a \vert $ 

input **number** --> **function** `abs()`, `math.fabc()`, `np.abs()` $\to$ output **number**$\mathbb{Q}$

input **array** --> **function** `np.abs()` $\to$ output **array**


In [70]:
b = -34
c = -3.45
x = np.array([-3,3,64])

print(abs(b)) # absolute value
print(abs(c))
print(math.fabs(c))

print(np.abs(x))

34
3.45
3.45
[ 3  3 64]


## *Exponention*

Potenz/*power*:

$ a^n = b $ 

a= base, n=power, b = exponent

input **number** $\mathbb{Q}$  $\to$ **function** `pow(base,exponent)`, $\to$ output as input **number** $\mathbb{Q}$

input **array,number**  $\to$ **function** `np.power(base,exponent)`, $\to$ output as input **array,number** 

Wurzel/*root*:

$\sqrt[n]{b} = a $ 

Quadratwurzel,*Squere root*: 

$\sqrt {b}=a $  , $\sqrt[2]{b} = a $

input **number** $\mathbb{Q}$ $\to$ **function** `math.sqrt()` $\to$ output **number** $\mathbb{Q}$

input **number,array** $\mathbb{Q}$ $\to$ **function** `np.sqrt()` $\to$ output **number,array** $\mathbb{Q}$

Qubikwurzel,*Cubic root*: 

 $\sqrt[3]{b} = a $

input **number,array** $\mathbb{Q}$ $\to$ **function** `np.cbrt()` $\to$ output **number,array** $\mathbb{Q}$

Logarithmus/*logarithm*

$\log_a b = n$


 $a = 2$  
 
$\log_2 b $ (binäre,duale)

$a = 10$   

 $\lg b = \log_{10} b$,(decadishe) 

exponent function:

**Irationale number,constant** `np.e`, $e \in \mathbb{R}$ 

$a = e$  

$\ln b  = \log_e b$ (natürliche)


In [63]:
x = np.array([1.2,2.3,3.4]) #array

print(pow(2,4)) #num
print(np.power(x,3))

print()
print(math.sqrt(20))
print(np.sqrt(x))
print(np.cbrt(x))
print()

print(math.log10(400))
print(math.log2(8))
print(math.log(12))

16
[ 1.728 12.167 39.304]

4.47213595499958
[1.09544512 1.51657509 1.84390889]
[1.06265857 1.32000612 1.5036946 ]

2.6020599913279625
3.0
2.4849066497880004


## Folge,Reihe *Sequence*

Folge:

 $(a_n)= , n \in \mathbb{N}$  **integer**  

Reihe: 

$a_n, a_{n+1}, ... a_N$

Folge:
$(a_n)_{n=0}^{\infty}$ 

 **function** `np.array([])`, `np.linspace()`, `np.arange()` $\to$ output **array** $\in \mathbb{Q}$

 

In [65]:
print(np.array([1,2,3,4]))
print(np.linspace(1,10,5))
print(np.arange(1,20,3))

[1 2 3 4]
[ 1.    3.25  5.5   7.75 10.  ]
[ 1  4  7 10 13 16 19]


## Limits

limit of Function:

$\lim_{x\to +\infty} f(x) $

$$\lim_{x\to -\infty} f(x)$$

$$\lim_{x\to 0} f(x)$$

## Summe

$\sum\limits_{n=1}^N a_n$ 

$$\sum_{n=1}^N a_n$$

input **array,number** $\mathbb{Q}$ $\to$  **function** `np.sum()`$\to$ output **array,number** $\mathbb{Q}$

In [86]:
print(np.sum([1,2]))

a= np.array([1,4,6,15])
print(np.sum(a))


3
26


## Product 

$\prod\limits_{n=1}^N a_n$

$$\prod_{n=1}^N a_n$$

### Scalar, Number : 

input **number** $\mathbb{Q}$ $\to$ **function** `np.multiply()` $\to$ output **number** $\mathbb{Q}$

input **array** $\mathbb{Q}$ $\to$ **function** `np.multiply()` elementweise! $\to$ output **array!** $\mathbb{Q}$

### Vector $ \vec v $

dot product, inner product : 

input **1-d array** $\to$ **function** `np.dot()` --> output **number!** $\mathbb{Q}$

cross product,  Outer product:

input **1-d array** $\to$ **function** `np.outer()` --> output **2-d array!** $matrix$



### Matrix

dot product, inner product : 

input **2-d array** $\to$ **function** `np.dot()` --> output **2-d array**

cross product,  Outer product:

input **2-d array** $\to$ **function** `np.outer()` --> output **2-d array**

In [77]:
v1 = np.array([2,5,4,7])
v2 = np.array ([4,1,0,2])

print(np.multiply(2,4))
print(np.multiply(v1,v2))


print(np.dot(v1,v2))
print(np.outer(v1,v2))


8
[ 8  5  0 14]
27
[[ 8  2  0  4]
 [20  5  0 10]
 [16  4  0  8]
 [28  7  0 14]]


In [90]:
m1 = np.random.randn(2,5)
m2 = np.random.randn(5,2)
m3= np.random.randn(3,4)

print(m1)
print()
print(m2)
print()
#print(np.dot(m1,m2))
print(np.outer(m1,m3))

[[-1.38344038  1.69262172 -0.57730663 -0.5601276   1.0769295 ]
 [-1.16479605 -0.2605436   0.976977   -0.53262337  0.4175798 ]]

[[-1.45807219 -2.77399257]
 [-0.65078109 -0.84688835]
 [-0.38178608  0.37436168]
 [-1.60036722 -1.44853992]
 [-0.69397899  0.5716141 ]]

[[-1.95029396 -2.56074689 -1.08803821 -0.86422654 -0.45228359 -0.22877077
  -1.70613014 -1.14113632  1.33708728  1.02595033 -0.20595521  1.92748116]
 [ 2.38615986  3.13304127  1.33120092  1.05737019  0.55336322  0.27989813
   2.08742853  1.39616578 -1.63590929 -1.25523718  0.25198358 -2.3582487 ]
 [-0.81385338 -1.06859405 -0.45403595 -0.36063984 -0.18873695 -0.09546554
  -0.71196436 -0.47619368  0.55796358  0.42812682 -0.08594466  0.80433365]
 [-0.78963538 -1.03679568 -0.44052511 -0.3499082  -0.18312066 -0.09262475
  -0.69077829 -0.46202349  0.54136015  0.41538696 -0.08338718  0.78039893]
 [ 1.51819272  1.99339554  0.84697575  0.67275112  0.352077    0.17808501
   1.3281251   0.8883096  -1.04084626 -0.79864387  0.16032439 -1.

## Polynomial

### Coefficient

binomial coefficiant  $\binom n k $

factorial $n!$

## *Unit circle*
 
$ \pi $  --> **function** `math.pi` ,  `np.pi`--> output **float** constant
  

In [10]:
pi_= math.pi
pi_=np.pi
print(pi_)
print(f"PI is {pi_:.2f}")

3.141592653589793
PI is 3.14


## Min and Max

$\min$

$\max$



In [34]:
x = 2
y = 3
z = 4
print(min(x, y, z))
print(max(x, y, z))

2
4


# Random 

In [102]:
#gives any number 0-1
x =random.random() 

#retun any int in range
y = random.randint(2,89)

#any number
b = np.random.randn()


print(x)
print(y)
print(b)

0.540361812294099
72
-1.3233794668779055


In [96]:

#vector
print(np.random.randn(2))
print()
#matrix 2-d
print(np.random.randn(2,4))


[-1.26903647  0.75436172]

[[-0.31264255  0.77652316  0.79521489  0.86956593]
 [ 0.32730623  0.27833177 -0.19675496 -0.59088549]]


In [97]:

#matrix 3-d
print(np.random.randn(2,4,3))

[[[ 0.41662009  1.55392377 -0.21836108]
  [-0.76785325  0.38755233 -1.36191683]
  [-0.71115364 -1.0180072   0.81776521]
  [ 0.21820659  1.00431647 -0.30568904]]

 [[-0.74973994 -1.22327395  0.06500939]
  [ 0.51139733 -0.05192831  3.3649887 ]
  [-1.51732304 -1.67389903  0.63609955]
  [ 0.31400008  0.04240569 -0.84970516]]]
